version: 2.1

jobs:
    build_and_test:
        docker:
            - image: 'circleci/rust:latest'
        environment:
            - ROCKET_ENV: 'production'
        steps:
            - checkout
            - run:
                  name: 'Install Rust nightly'
                  command: 'rustup default nightly'
            - run:
                  name: 'Install dependencies'
                  command: 'cargo build --release'
            - run:
                  name: 'Run tests'
                  command: 'cargo test'

workflows:
    version: 2
    build_and_test_workflow:
        jobs:
            - build_and_test
